/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ercSol from "./Erc.sol";
export type { ercSol };
export type { Ierc } from "./Ierc";
export * as factories from "./factories";
export type { ERC20 } from "./Erc.sol/ERC20";
export { ERC20__factory } from "./factories/Erc.sol/ERC20__factory";
export { Ierc__factory } from "./factories/Ierc__factory";
