/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./Erc20.sol";
export * as factoryContractSol from "./FactoryContract.sol";
export * as ierc20Sol from "./Ierc20.sol";
