/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./Erc20.sol";
export type { erc20Sol };
import type * as factoryContractSol from "./FactoryContract.sol";
export type { factoryContractSol };
import type * as ierc20Sol from "./Ierc20.sol";
export type { ierc20Sol };
export * as factories from "./factories";
export type { ERC20 } from "./Erc20.sol/ERC20";
export { ERC20__factory } from "./factories/Erc20.sol/ERC20__factory";
export type { TokenFactory } from "./FactoryContract.sol/TokenFactory";
export { TokenFactory__factory } from "./factories/FactoryContract.sol/TokenFactory__factory";
export type { Ierc } from "./Ierc20.sol/Ierc";
export { Ierc__factory } from "./factories/Ierc20.sol/Ierc__factory";
